#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

gfsh run --file=${DIR}/gfsh/stop-server-3.gfsh

sleep 60

gfsh run --file=${DIR}/gfsh/start-server-3.gfsh

