#!/usr/bin/env bash

gfsh stop server --dir members/server2

# sleep 10s

gfsh -e connect "start server --name server2 --dir members/server2 --locators 127.0.0.1[10334] --server-port=0 --J=-Dprometheus.metrics.port=9002"


